### PR TITLE
Esd method

### PR DESCRIPTION
**Pull request by wence-**
Make entity_support_dofs a method of FiniteElementBase, rather than a free function (keep that for backwards compatibility).

### CODE REVIEW

**Comment by miklos1** [comment]
So far the difference does not seem significant. Do you plan to have specific versions of `entity_support_dofs` for different finite element classes, or what is the reason for the change?

**Comment by wence-** [comment]
Note that you now get the `entity_support_dofs` for all entities, rather than the specified entity (mirroring `entity_closure_dofs`).  I need all of them for the extruded layers stuff.  I guess I could just make the entity optional in the free function instead.  But it has always seemed strange to me how `e_c_d` is a method, but `e_s_d` is not.

**Comment by miklos1** [comment]
OK, it used to be a method at some point in the past.

**Comment by wence-** [comment]
Although this is ok, it runs into problems for enriched elements in 3D.  Since no-one really uses `entity_support_dofs`, and I only want this for "completeness" in extrusion, I will drop this for now.

**Pull request closed without merging**
